//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingAutomat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int id { get; set; }
        public Nullable<int> cashOwnerId { get; set; }
        public Nullable<int> cashTypeId { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual CashOwner CashOwner { get; set; }
        public virtual CashType CashType { get; set; }
    }
}
