//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingAutomat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> isNewUser { get; set; }
        public Nullable<System.DateTime> saleTime { get; set; }
    }
}
